name: Feature Request
description: Suggest an enhancement or new feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: How would you use this feature?
      render: text

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information, screenshots, or links
