# CI workflow for CSS/Design System libraries (OmniUI, OmniDS)
# Runs CSS lint, build, and tests on PRs and pushes to main
#
# Usage: Copy to .github/workflows/ci.yml

name: CI

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  check:
    name: Lint, Build, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # CSS Linting (Stylelint)
      - name: Lint CSS
        run: npm run lint:css --if-present

      # JS/TS Linting (ESLint)
      - name: Lint JS
        run: npm run lint:js --if-present
        continue-on-error: true  # Don't fail if no JS linting configured

      # Build CSS and JS
      - name: Build
        run: npm run build

      # Run tests
      - name: Test
        run: npm test --if-present

      # Build documentation/examples (optional)
      # - name: Build Docs
      #   run: npm run build:docs --if-present
