# CI workflow for .NET/C# projects
# Runs build, test, and format check on PRs and pushes to main
#
# Usage: Copy to .github/workflows/ci.yml
# Update the solution/project paths as needed

name: CI

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      # Check formatting (optional)
      # - name: Check Formatting
      #   run: dotnet format --verify-no-changes

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal

      # Code coverage (optional)
      # - name: Test with Coverage
      #   run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"
      #
      # - name: Upload Coverage
      #   uses: codecov/codecov-action@v3
