# Deploy documentation to GitHub Pages
# Manual trigger from Actions tab
#
# Usage: Copy to .github/workflows/pages.yml
# Update the build commands and output path for your project
#
# Prerequisites:
#   1. Go to Settings > Pages
#   2. Source: GitHub Actions

name: Deploy to GitHub Pages

on:
  # Manual trigger only - run from Actions tab
  workflow_dispatch:

  # Or enable auto-deploy on push to main:
  # push:
  #   branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

# Only one deployment at a time
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Customize this section for your docs structure:
      # Option 1: Built docs in dist/
      # - name: Copy dist to docs
      #   run: cp -r dist docs/site/

      # Option 2: Separate docs build
      # - name: Build docs
      #   run: npm run build:docs

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Update this path to your docs output directory:
          path: 'docs/site'

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
